 const data = [
    {
      key: '1',
      item_name: 'HP x360',
      ram: 32,
      ram_slot:2,
      hard_drive: 1,
    },
    {
      key: '2',
      item_name: 'HP x360 envy',
      ram: 16,
      ram_slot:2,
      hard_drive: 1024,
    },
    {
      key: '3',
      item_name: 'Dell inspiron',
      ram: 8,
      ram_slot:2,
      hard_drive: '512',
    },
    {
      key: '4',
      item_name: 'Lenovo thinkpad',
      ram: 4,
      ram_slot: 2,
      hard_drive: 512,
    },
    {
      key: '1',
      item_name: 'HP x360',
      ram: 32,
      ram_slot:2,
      hard_drive: 1,
    },
    {
      key: '2',
      item_name: 'HP x360 envy',
      ram: 16,
      ram_slot:2,
      hard_drive: 1024,
    },
    {
      key: '3',
      item_name: 'Dell inspiron',
      ram: 8,
      ram_slot:2,
      hard_drive: '512',
    },
    {
      key: '4',
      item_name: 'Lenovo thinkpad',
      ram: 4,
      ram_slot: 2,
      hard_drive: 512,
    },
    {
      key: '1',
      item_name: 'HP x360',
      ram: 32,
      ram_slot:2,
      hard_drive: 1,
    },
    {
      key: '2',
      item_name: 'HP x360 envy',
      ram: 16,
      ram_slot:2,
      hard_drive: 1024,
    },
    {
      key: '3',
      item_name: 'Dell inspiron',
      ram: 8,
      ram_slot:2,
      hard_drive: '512',
    },
    {
      key: '4',
      item_name: 'Lenovo thinkpad',
      ram: 4,
      ram_slot: 2,
      hard_drive: 512,
    },
    {
      key: '1',
      item_name: 'HP x360',
      ram: 32,
      ram_slot:2,
      hard_drive: 1,
    },
    {
      key: '2',
      item_name: 'HP x360 envy',
      ram: 16,
      ram_slot:2,
      hard_drive: 1024,
    },
    {
      key: '3',
      item_name: 'Dell inspiron',
      ram: 8,
      ram_slot:2,
      hard_drive: '512',
    },
    {
      key: '4',
      item_name: 'Lenovo thinkpad',
      ram: 4,
      ram_slot: 2,
      hard_drive: 512,
    },
  ];
  
  export default data;